[workspace]
members = [
    "aitos",
    "aitos-embassy",
    "displaitor",
    "qoa_decoder",
    "simulaitor",
]
resolver = "2"

[workspace.dependencies]
embedded-error-chain = "^1.0"
embedded-graphics = "^0.8"
